/**
 * Copyright © 2016-2026 The Thingsboard Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.thingsboard.server.common.data.ai.solution;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;

import java.io.Serializable;
import java.util.List;

/**
 * Root of the "architecture specification" produced by the AI Solution Creator.
 * <p>
 * This is the stable contract shared between three consumers:
 * <ul>
 *     <li>the LLM, which is instructed to emit exactly this JSON shape;</li>
 *     <li>the UI, which renders it (Basic tables + Advanced JSON editor);</li>
 *     <li>the {@code AiSolutionInstaller}, which turns it into real ThingsBoard entities.</li>
 * </ul>
 * Everything is intentionally lenient ({@link JsonIgnoreProperties}) so that a slightly
 * imperfect model response still deserializes and can be corrected by the user.
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Schema(description = "Architecture specification generated by the AI Solution Creator")
public record AiSolutionSpec(
        @Schema(description = "Human-readable solution name", example = "Indoor Smart Parking Monitoring")
        String name,

        @Schema(description = "Short description of what the solution does")
        String description,

        @Schema(description = "Device profiles, asset profiles and customers to create")
        EntityProfilesSpec entityProfiles,

        @Schema(description = "Identity and access management: roles, entity groups, users and permissions")
        IamSpec iam,

        @Schema(description = "Calculated fields derived from raw telemetry")
        List<CalculatedFieldSpec> calculatedFields,

        @Schema(description = "Alarm rules configured on device profiles")
        List<AlarmSpec> alarms,

        @Schema(description = "Role-oriented dashboards, designed in the second step of the wizard")
        List<DashboardSpec> dashboards
) implements Serializable {

    public EntityProfilesSpec entityProfilesOrEmpty() {
        return entityProfiles != null ? entityProfiles : new EntityProfilesSpec(List.of(), List.of(), List.of());
    }

    public IamSpec iamOrEmpty() {
        return iam != null ? iam : new IamSpec(List.of(), List.of(), List.of(), List.of());
    }

    public List<CalculatedFieldSpec> calculatedFieldsOrEmpty() {
        return calculatedFields != null ? calculatedFields : List.of();
    }

    public List<AlarmSpec> alarmsOrEmpty() {
        return alarms != null ? alarms : List.of();
    }

    public List<DashboardSpec> dashboardsOrEmpty() {
        return dashboards != null ? dashboards : List.of();
    }

}
